#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim-arm32v7 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Server/BlazorWasmRegexTest.Server.csproj", "Server/"]
COPY ["Client/BlazorWasmRegexTest.Client.csproj", "Client/"]
COPY ["Shared/BlazorWasmRegexTest.Shared.csproj", "Shared/"]
RUN dotnet restore "Server/BlazorWasmRegexTest.Server.csproj"
COPY . .
WORKDIR "/src/Server"
RUN dotnet build "BlazorWasmRegexTest.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BlazorWasmRegexTest.Server.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BlazorWasmRegexTest.Server.dll"]